### ISSUE TITLE
 gdal.js not symlinked in thumbnail_map or tile_tiff example directories

### ISSUE THREAD

**Issue by kellyi** [ddohler/gdal-js#31]
I set this project up and ran the examples and everything's working well except that it appears that `worker.js` can't import `gdal.js` in the `thumbnail_map` or `tile_tiff` dirs.

Looking through those dirs it appears that the `gdal.data` and `gdal.wasm` files have been symlinked, but not `gdal.js`.

**Comment by ddohler** [comment]
Good catch! I've fixed this on `develop-js` and it'll make it over to `master-js` then next time there's a release.
