### ISSUE TITLE
Not getting the inspect_vector example to work?

### ISSUE THREAD

**Issue by SimonsUnikaNamn** [ddohler/gdal-js#47]
First of all, amazingly cool project, I have used it for `GDAL_WARP` and it is working beautifully.

But now I want to use ogr2ogr and tried to get the `inspect_vector` example working, but the log says

```
stderr: wasm streaming compile failed: TypeError: Cannot read properties of undefined (reading 'arguments')
worker.js:47 stderr: falling back to ArrayBuffer instantiation
```

and 

```
        initialized = true;
```

is never run.

Any ideas about this?

![Skärmavbild 2022-11-16 kl  16 00 02](https://user-images.githubusercontent.com/1564038/202215584-1ae15d8b-c7e1-4029-8333-7cc792292ce8.png)

**Comment by ddohler** [comment]
Hi! There was an earlier issue with `inspect_vector` missing a symlink: #45 , but that should have been fixed -- can you double-check that you're on the latest commit on the `develop-js` branch?

**Comment by SimonsUnikaNamn** [comment]
Thank you, I still had the old built binaries!

🙌
