### ISSUE TITLE
conversion of osm file into shape file

### ISSUE THREAD

**Issue by shalini-whiz** [ddohler/gdal-js#57]
Is there any way to convert .osm file into shape file via nodejs environment ?

**Comment by ddohler** [comment]
@shalini-whiz You can use ogr2ogr to do this: https://gis.stackexchange.com/questions/215776/convert-an-osm-file-to-a-shapefile-with-the-same-attributes . `gdal-js` includes ogr2ogr, but hasn't been tested in a Node environment. My first suggestion is to try executing a shell command to call ogr2ogr.

Closing this as it is not `gdal-js`-specific.
